export * from './auxiliatura.interface';
export * from './dependencia.interface';
export * from './prioridad.interface';
export * from './sexo.interface';
export * from './genero.interface';
export * from './motivo.interface';
export * from './documento-identidad.interface';
export * from './visita.interface';
export * from './funcionario.interface';
