export * from './funcionarios.service';
export * from './personas.service';
export * from './persona-direccion.service';
export * from './documento-identidad-persona.service';
export * from './visitas.service';
export * from './expendiente.service';
export * from './expediente-persona.service';
export * from './expediente-hecho.service';
export * from './expediente-hecho-archivo.service';
